Transform: AWS::Serverless-2016-10-31
Resources:
  TypeScriptTemplateGreeterLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: TypeScriptTemplateGreeterLambda
      CodeUri: hello-world
      Handler: src/index.handler
      Runtime: nodejs22.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment: {}
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - src/index.ts
  TypeScriptTemplateGreeterLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${TypeScriptTemplateGreeterLambda}
