name: Delete

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
      - name: Delete
        run: sam delete --no-prompts